version: '3.6'
services:
  auth:
    build: ./auth
    ports:
      - 31197:5000
    volumes:
      - ./auth/app.py:/app.py
    read_only: true
  backend:
    build: ./backend
    working_dir: /home/ctf
    entrypoint: /etc/run_xinetd.sh
    read_only: true
